### ISSUE TITLE
Cannot destructure property `login` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by omjadas** [ClearTax/jira-lint#24]
![image](https://user-images.githubusercontent.com/6400093/81130354-d3ce6880-8f8a-11ea-967c-bab64c861ad3.png)

**Comment by TheRealWaldo** [comment]
Seeing the same.

**Comment by gagan-hotstar** [comment]
same issue

**Comment by asbjornu** [comment]
Yeah, same. [Here's a publicly available GitHub Actions run with the error](https://github.com/asbjornu/test/runs/5182470906?check_suite_focus=true):

```js
{
  error: TypeError: Cannot destructure property `login` of 'undefined' or 'null'.
      at /home/runner/work/_actions/cleartax/jira-lint/master/lib/index.js:1:21210
      at Generator.next (<anonymous>)
      at /home/runner/work/_actions/cleartax/jira-lint/master/lib/index.js:1:19906
      at new Promise (<anonymous>)
      at n (/home/runner/work/_actions/cleartax/jira-lint/master/lib/index.js:1:19654)
      at run (/home/runner/work/_actions/cleartax/jira-lint/master/lib/index.js:1:20939)
      at Object.131 (/home/runner/work/_actions/cleartax/jira-lint/master/lib/index.js:1:23551)
      at __webpack_require__ (/home/runner/work/_actions/cleartax/jira-lint/master/lib/index.js:1:154)
      at startup (/home/runner/work/_actions/cleartax/jira-lint/master/lib/index.js:1:291)
      at module.exports.0 (/home/runner/work/_actions/cleartax/jira-lint/master/lib/index.js:1:323)
}
Error: Cannot destructure property `login` of 'undefined' or 'null'.
```

**Comment by asbjornu** [comment]
It would be a lot easier to debug this problem if a non-minimized version of the action was provided, somehow. If one can be provided (in a separate branch, for instance), I can run against it and give you a new and much more informative stack trace. But it seems like this is the problematic (minimized) expression:

```js
const{payload:{repository:f,organization:{login:y},pull_request:b}}=o.context
```

If that's correct, this may be the source:

https://github.com/ClearTax/jira-lint/blob/0b90e54c614ba320d44d4d2b02df4c0c7fa70f89/src/main.ts#L64-L70

**Comment by asbjornu** [comment]
I'm not sure, but I believe that this would fix the problem:

```diff
diff --git a/src/main.ts b/src/main.ts
index 10d28e9..4b55e79 100755
--- a/src/main.ts
+++ b/src/main.ts
@@ -64,7 +64,6 @@ async function run(): Promise<void> {
     const {
       payload: {
         repository,
-        organization: { login: owner },
         pull_request: pullRequest,
       },
     } = github.context;
@@ -73,7 +72,7 @@ async function run(): Promise<void> {
       throw new Error(`Missing 'repository' from github action context.`);
     }

-    const { name: repo } = repository;
+    const { name: repo, owner: { login: owner } }  = repository;

     const {
       base: { ref: baseBranch },
```

**Comment by asbjornu** [comment]
I submitted #55 to fix this problem.

**Comment by asbjornu** [comment]
As suggested by @maddhruv in https://github.com/ClearTax/jira-lint/pull/56#issuecomment-1119238816, I've forked and fixed this and a lot of other issues in [`action-jira-linter`](https://github.com/marketplace/actions/action-jira-linter).
