### ISSUE TITLE
Error: error for dependabots PR's

### ISSUE THREAD

**Issue by nmyalik** [ClearTax/jira-lint#39]
I suppose that PR's created by dependabot should be skipped by default. But i saw error 
```{
  error: Error: Input required and not supplied: jira-token
      at Object.getInput (/home/runner/work/_actions/cleartax/jira-lint/master/lib/index.js:1:113632)
      at p (/home/runner/work/_actions/cleartax/jira-lint/master/lib/index.js:1:20233)
      at /home/runner/work/_actions/cleartax/jira-lint/master/lib/index.js:1:21131
      at Generator.next (<anonymous>)
      at /home/runner/work/_actions/cleartax/jira-lint/master/lib/index.js:1:19906
      at new Promise (<anonymous>)
      at n (/home/runner/work/_actions/cleartax/jira-lint/master/lib/index.js:1:19654)
      at run (/home/runner/work/_actions/cleartax/jira-lint/master/lib/index.js:1:20939)
      at Object.131 (/home/runner/work/_actions/cleartax/jira-lint/master/lib/index.js:1:23551)
      at __webpack_require__ (/home/runner/work/_actions/cleartax/jira-lint/master/lib/index.js:1:154)
}
Error: Input required and not supplied: jira-token
```
Branch name:  `dependabot/npm_and_yarn/fortawesome/pro-regular-svg-icons-5.15.3`
Jira lint file: 
```name: jira-lint
on: [pull_request]

jobs:
  jira-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: cleartax/jira-lint@master
        name: jira-lint
        with:
          github-token: <secret>
          jira-token: <token>
          jira-base-url: <attlasian-base-url>
          skip-branches: '^(master)$'
          skip-comments: false
          pr-threshold: 1000
```
I see expected message only if i use `skip-branches: '^master$|^dependabot.*'`.

**Comment by nmyalik** [comment]
Closed depends on[ this article ](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/)
